// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SnowmobileShop.Data;

#nullable disable

namespace SnowmobileShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.13");

            modelBuilder.Entity("SnowmobileShop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Forename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("SnowmobileShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("SnowmobileShop.Models.ProductLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RentalTimeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShoppingCartId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RentalTimeId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("ProductLines", (string)null);
                });

            modelBuilder.Entity("SnowmobileShop.Models.RentalDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("RentalDays", (string)null);
                });

            modelBuilder.Entity("SnowmobileShop.Models.RentalTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("From")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RentalDayId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("To")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RentalDayId");

                    b.ToTable("RentalHours", (string)null);
                });

            modelBuilder.Entity("SnowmobileShop.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ShoppingCarts", (string)null);
                });

            modelBuilder.Entity("SnowmobileShop.Models.SnowmobileType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SnowmobileTypes", (string)null);
                });

            modelBuilder.Entity("SnowmobileShop.Models.Snowmobile", b =>
                {
                    b.HasBaseType("SnowmobileShop.Models.Product");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineCapacity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Horsepower")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ListPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SnowmobileTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearOfProduction")
                        .HasColumnType("INTEGER");

                    b.HasIndex("SnowmobileTypeId");

                    b.ToTable("Snowmobiles", (string)null);
                });

            modelBuilder.Entity("SnowmobileShop.Models.Trip", b =>
                {
                    b.HasBaseType("SnowmobileShop.Models.Product");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Hours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.ToTable("Trips", (string)null);
                });

            modelBuilder.Entity("SnowmobileShop.Models.ProductLine", b =>
                {
                    b.HasOne("SnowmobileShop.Models.Order", null)
                        .WithMany("ProductLines")
                        .HasForeignKey("OrderId");

                    b.HasOne("SnowmobileShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnowmobileShop.Models.RentalTime", "RentalTime")
                        .WithMany()
                        .HasForeignKey("RentalTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnowmobileShop.Models.ShoppingCart", null)
                        .WithMany("Lines")
                        .HasForeignKey("ShoppingCartId");

                    b.Navigation("Product");

                    b.Navigation("RentalTime");
                });

            modelBuilder.Entity("SnowmobileShop.Models.RentalDay", b =>
                {
                    b.HasOne("SnowmobileShop.Models.Product", "Product")
                        .WithMany("RentalDays")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SnowmobileShop.Models.RentalTime", b =>
                {
                    b.HasOne("SnowmobileShop.Models.RentalDay", "RentalDay")
                        .WithMany("RentalHours")
                        .HasForeignKey("RentalDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentalDay");
                });

            modelBuilder.Entity("SnowmobileShop.Models.Snowmobile", b =>
                {
                    b.HasOne("SnowmobileShop.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("SnowmobileShop.Models.Snowmobile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnowmobileShop.Models.SnowmobileType", "SnowmobileType")
                        .WithMany()
                        .HasForeignKey("SnowmobileTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SnowmobileType");
                });

            modelBuilder.Entity("SnowmobileShop.Models.Trip", b =>
                {
                    b.HasOne("SnowmobileShop.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("SnowmobileShop.Models.Trip", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SnowmobileShop.Models.Order", b =>
                {
                    b.Navigation("ProductLines");
                });

            modelBuilder.Entity("SnowmobileShop.Models.Product", b =>
                {
                    b.Navigation("RentalDays");
                });

            modelBuilder.Entity("SnowmobileShop.Models.RentalDay", b =>
                {
                    b.Navigation("RentalHours");
                });

            modelBuilder.Entity("SnowmobileShop.Models.ShoppingCart", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
